# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 405a2c25f83545d2f5af7d12cb7e9c2faff607108e730c5fb6cbd45a9a43c486be897dd28fd31dfe5b44d54304889720e5608bfafe9fae05156aa482b1b562b5

test:
  secret_key_base: bd7d0519ec3e7ef98a64a67858d5eb94f4669f9b8cc52bcd10a1997ac04880db92464b968f64b076884addaf58e7e799e66c57270ad190271e006aa92ec850ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
